spring:
  application:
    name: decola-tech
  datasource:
    url: jdbc:postgresql://localhost:5438/decola-tech
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080
#management:
#  endpoints:
#    web:
#      exposure:
#        include:  *